name: Production Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Deploy to server
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
          
          # Copy files to server
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/deploy_key" \
            --exclude='.git' \
            --exclude='__pycache__' \
            --exclude='.env' \
            --exclude='venv' \
            --exclude='.github' \
            ./ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ vars.DEPLOY_PATH }}/
          
          # Deploy with PM2
          ssh -i ~/.ssh/deploy_key ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'ENDSSH'
            cd ${{ vars.DEPLOY_PATH }}
            
            # Install Python dependencies on server
            python3 -m venv venv || true
            source venv/bin/activate
            pip install -r requirements.txt
            
            # Create .env file with production variables
            cat > .env << EOF
            TWILIO_PHONE_NUMBER=${{ secrets.TWILIO_PHONE_NUMBER }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            PORT=${{ vars.PORT }}
            HOST=${{ vars.HOST }}
            EOF
            
            # Stop existing PM2 process if running
            pm2 delete speech-assistant-api || true
            
            # Start new PM2 process
            pm2 start main.py \
              --name speech-assistant-api \
              --interpreter venv/bin/python \
              --log-date-format "YYYY-MM-DD HH:mm:ss Z" \
              --merge-logs \
              --time
            
            # Save PM2 process list
            pm2 save
            
            # Show status
            pm2 status speech-assistant-api
          ENDSSH
          
          # Cleanup SSH key
          rm -f ~/.ssh/deploy_key